### ISSUE TITLE
Add support of docker "swarm mode"

### ISSUE THREAD

**Issue by interair** [codeabovelab/haven-platform#3]
Provide support of the new "Swarm mode" available in Docker 1.13 and above.

**Comment by wayerr** [comment]
Roadmap:
* implement docker DTOs (possibly already finished)
* extends DockerService for new api methods
* make new cluster kind and do some refactoring. This feature allow to connect for different nodes for orchestration, but current RealCluster does not support this

**Comment by wayerr** [comment]
Investigation show that we need to wait docker 0.13 release due to https://github.com/docker/docker/pull/27910
