### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by ZloyRabadaber** [codeabovelab/haven-platform#35]
I reup haven:

1. stop and rm haven container
2. stop and rm etcd0 container
3. delete data dirs
4. up etcd0 and haven conteiners
But i canot login with admin/password
what am I doing wrong?

**Comment by wayerr** [comment]
Follow command remove admin user of Haven system from etcd storage:
```etcdctl rm /cluman/users/admin```

after it you maybe need restart haven, and it will use default admin settings
