### ISSUE TITLE
impossible to log in over https

### ISSUE THREAD

**Issue by ZloyRabadaber** [codeabovelab/haven-platform#36]
I use https to access the web interface Haven. and it is impossible to log in.
maybe I'm doing something wrong?

**Comment by wayerr** [comment]
Haven does not provide https out of box, and we not test how it work with it. Probably, you done customization of Haven container or access through proxy - we need know it for investigation of problem.

**Comment by wayerr** [comment]
Now i test through proxy: we have UI bug - requests from ui loaded through https  is sent to http.

**Comment by ZloyRabadaber** [comment]
спасибо. буду ждать фикса.

**Comment by Anselm21** [comment]
Fixed.

**Comment by interair** [comment]
codeabovelab/cluster-manager:1.1.4
