### ISSUE TITLE
Add "services" tab @ cluster UI

### ISSUE THREAD

**Issue by interair** [codeabovelab/haven-platform#37]
see /swagger-ui.html#/service-api 
and /swagger-ui.html#!/cluster-api/listServicesUsingGET

**Comment by interair** [comment]
Actions:

1. Create
2. Delete
3. Get
4. Update
5. Scale

**Comment by wayerr** [comment]
sample of service:  https://github.com/codeabovelab/haven-api-tests/blob/master/docker_cluster/ping-service.json (from [here](https://github.com/codeabovelab/haven-api-tests/blob/master/test_docker_cluster.js#L62))

**Comment by Anselm21** [comment]
Added to 'dev' branch.
