### ISSUE TITLE
Allow to chose type of cluster (stand alone swarm or swarm-mode) during creating new cluster

### ISSUE THREAD

**Issue by interair** [codeabovelab/haven-platform#39]
see /swagger-ui.html#!/cluster-api/updateClusterUsingPATCH

was added 
`  "managers": [
    "string"
  ] List of node names which will be used as managers. `
and 
`type: "SWARM"(standalone swarm cluster)/"DOCKER" (docker in swarm-mode cluster).`

**Comment by Anselm21** [comment]
Added "managers" and "type" to ClusterAdd dialog, "type" column to clusters list. Pushed to dev.
