### ISSUE TITLE
Behavior of data table in application pages are inconsistent

### ISSUE THREAD

**Issue by mchwang** [codeabovelab/haven-platform#40]
On some pages, the entire section of the page is not rendered until the the data is loaded.  On other pages, most of the pages are rendered except for the data that are still being returned from server.  The behavior should be consolidated to be the latter where most of the pages are rendered to give user a better experience.  

Also if there are no data in a data table, some tables are empty while others show a friendly message.  We should always show a friendly message.

**Comment by Anselm21** [comment]
Fixed.
