### ISSUE TITLE
Add ability to clone an existing container

### ISSUE THREAD

**Issue by mchwang** [codeabovelab/haven-platform#42]
I would like to be able to "clone" an existing container but be able to modify the different attributes such as env. variables, volume settings, tags, etc before starting.

**Comment by interair** [comment]
but we already have scale

**Comment by wayerr** [comment]
Exploration show that it can be fully implemented on UI side, for both containers and services.
Algorithm like 'edit' load source of container/service to UI and after edit post its to appropriate 'create' api method.

@interair  what you think about this?

**Comment by mchwang** [comment]
That would fulfill the need.  Users often launch images and miss a parameter so it's very tedious to re-input all of the parameters again.

**Comment by Anselm21** [comment]
added "clone container" feature, pushed to dev branch.
