### ISSUE TITLE
nodes is holded after delete its cluster

### ISSUE THREAD

**Issue by wayerr** [codeabovelab/haven-platform#44]
Steps to reproduce:

- delete cluster with nodes
- try to create new cluster (*important* do not reload page) with nodes of deleted cluster

workaround: reload page after cluster deleting

**Comment by Anselm21** [comment]
Can't reproduce it (I do not refresh page), actually, after cluster is deleted, ui pulls the list of orphans nodes from server.

**Comment by wayerr** [comment]
Sorry, backend send empty list of nodes at first time
