### ISSUE TITLE
Adjusting of "Node" doesn't work when cloning container

### ISSUE THREAD

**Issue by stepan-romankov** [codeabovelab/haven-platform#53]
### Steps:
- Open /clusters/{cluster}
- Choose a container and select "Clone"
- Change "Node" to any node other then current
- Press "Create container"

### Result:
- Container is started on the same node as original what is incorrect

**Comment by interair** [comment]
Issue was in priority of applying rules: information about preferred node exists explicitly in node combobox and in constraints

**Comment by interair** [comment]
1.2.3 Milestone
