### ISSUE TITLE
Non semantic versioning tags should not influence on images updates

### ISSUE THREAD

**Issue by stepan-romankov** [codeabovelab/haven-platform#54]
### Steps:
- Open /clusters/{name}/images
### Result:
- Image shouldn't be highlighted because of "latest" image tag

**Comment by Anselm21** [comment]
Done the fix - the 'latest' tag is highlighted only, if there is also a newer numerical tag.

**Comment by interair** [comment]
fixed in https://github.com/codeabovelab/haven-ui/commit/da5d3d5a9dd0a22d4583d0530f24f3833d570280
